name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04 # amd64
          - ubuntu-24.04-arm # arm64
          - macos-15-large # amd64
          - macos-15-xlarge # arm64
          - windows-2025 # am64
          - windows-11-arm # arm64
        node:
          - 20
          - 22
          - 24

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
      - run: npm ci
      - run: npm test
